### ISSUE TITLE
wait period before stable readout

### ISSUE THREAD

**Issue by petergullberg** [luetzel/sds011#1]
FYI, used your code for some testing, and found that the wait before reading the SDS011 was slightly short, which every 100 read created readings with good CRC, but the measurement was very unstable. Changed to 20 seconds, and the reading got stable.

**Comment by luetzel** [comment]
Hi Peter,
thats odd. Never had problems with CRC. We've built four sensor kits for our pupils and we always got stable readings. I cannot reproduce it over here.
Cheers,
/luetzel

**Comment by petergullberg** [comment]
Hi Lutezel,

CRC is correct on the all the readings, but with 10s between activation and readout, I occasionally get bad values.

2018-03-11 10:11:40;2.6;3.1
2018-03-11 10:13:11;2.3;2.7
2018-03-11 10:14:41;2.3;5.5
2018-03-11 10:19:12;4369.1;889.6
2018-03-11 10:20:42;3.3;5.1
2018-03-11 10:22:13;2.8;7.4
2018-03-11 10:23:43;3.1;5.4
2018-03-11 10:25:14;3.5;6.2

Anyhow it's for your information, it might be my sensor...

Cheers
\Peter

**Comment by luetzel** [comment]
OK, I see. This kind of error might be related to your power supply. It is important to avoid under-voltage which appears to be a frequent problem with USB-powered devices. What Pi version (with/without display) do you use?

**Comment by petergullberg** [comment]
I figured that could be a possible cause as well, but couldn't detect any major spikes with my fluke. I'm using a Raspberry PI 1, and no display (remote desktop), using a 2.5A power adapter. I will check other sources, but changing to 20s solved my problem. I might separate the power supply to the SDS011..

Thanks

**Comment by luetzel** [comment]
You should try to enter max_usb_current=1 into your /boot/config.txt, so that up to 1.2 Ampere can flow to your USB port.
